// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package persistence

import (
	"time"

	"github.com/blebon/blogroll-md/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPersistence creates a new instance of MockPersistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersistence {
	mock := &MockPersistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersistence is an autogenerated mock type for the Persistence type
type MockPersistence struct {
	mock.Mock
}

type MockPersistence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersistence) EXPECT() *MockPersistence_Expecter {
	return &MockPersistence_Expecter{mock: &_m.Mock}
}

// CutOff provides a mock function for the type MockPersistence
func (_mock *MockPersistence) CutOff() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CutOff")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockPersistence_CutOff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CutOff'
type MockPersistence_CutOff_Call struct {
	*mock.Call
}

// CutOff is a helper method to define mock.On call
func (_e *MockPersistence_Expecter) CutOff() *MockPersistence_CutOff_Call {
	return &MockPersistence_CutOff_Call{Call: _e.mock.On("CutOff")}
}

func (_c *MockPersistence_CutOff_Call) Run(run func()) *MockPersistence_CutOff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPersistence_CutOff_Call) Return(time1 time.Time) *MockPersistence_CutOff_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockPersistence_CutOff_Call) RunAndReturn(run func() time.Time) *MockPersistence_CutOff_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockPersistence
func (_mock *MockPersistence) Read() (types.Blogs, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 types.Blogs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (types.Blogs, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() types.Blogs); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Blogs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersistence_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockPersistence_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockPersistence_Expecter) Read() *MockPersistence_Read_Call {
	return &MockPersistence_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockPersistence_Read_Call) Run(run func()) *MockPersistence_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPersistence_Read_Call) Return(blogs types.Blogs, err error) *MockPersistence_Read_Call {
	_c.Call.Return(blogs, err)
	return _c
}

func (_c *MockPersistence_Read_Call) RunAndReturn(run func() (types.Blogs, error)) *MockPersistence_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockPersistence
func (_mock *MockPersistence) Write(blogs types.Blogs) error {
	ret := _mock.Called(blogs)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.Blogs) error); ok {
		r0 = returnFunc(blogs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPersistence_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockPersistence_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - blogs types.Blogs
func (_e *MockPersistence_Expecter) Write(blogs interface{}) *MockPersistence_Write_Call {
	return &MockPersistence_Write_Call{Call: _e.mock.On("Write", blogs)}
}

func (_c *MockPersistence_Write_Call) Run(run func(blogs types.Blogs)) *MockPersistence_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.Blogs
		if args[0] != nil {
			arg0 = args[0].(types.Blogs)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPersistence_Write_Call) Return(err error) *MockPersistence_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPersistence_Write_Call) RunAndReturn(run func(blogs types.Blogs) error) *MockPersistence_Write_Call {
	_c.Call.Return(run)
	return _c
}
